/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var tst = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[5,12],$V1=[2,9],$V2=[1,5],$V3=[1,6],$V4=[1,9],$V5=[1,12],$V6=[1,13],$V7=[1,14],$V8=[1,15],$V9=[1,16],$Va=[1,17],$Vb=[1,18],$Vc=[1,19],$Vd=[1,20],$Ve=[1,21],$Vf=[2,16],$Vg=[1,37],$Vh=[5,12,15,18,20,21],$Vi=[2,18],$Vj=[1,47],$Vk=[1,49];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"makefile":3,"statements":4,"EOF2":5,"statement":6,"rulestatement":7,"RECIPE_LINE":8,"INCLUDE":9,"variable_definition":10,"emptyline":11,"EOL":12,"RULESTART":13,"targetlist":14,"COLON":15,"targets2":16,"targets3":17,"PIPE":18,"inline_recipe_definition":19,"TARGET":20,"SEMICOLON":21,"INLINE_RECIPE":22,"inline_variable_definition":23,"multiline_variable_definition":24,"VARIABLE_SET_SIMPLE":25,"VARIABLE_VALUE":26,"VARIABLE_SET_RECURSIVE":27,"VARIABLE_SET_APPEND":28,"VARIABLE_SET_CONDITIONAL":29,"VARIABLE_SET_SHELL":30,"MULTILINE_VARIABLE_SET_SIMPLE":31,"MULTILINE_VARIABLE_VALUE":32,"MULTILINE_VARIABLE_END":33,"MULTILINE_VARIABLE_SET_RECURSIVE":34,"MULTILINE_VARIABLE_SET_APPEND":35,"MULTILINE_VARIABLE_SET_CONDITIONAL":36,"MULTILINE_VARIABLE_SET_SHELL":37,"optional_recipes":38,"recipes":39,"test":40,"dotest":41,"TST":42,"evt":43,"VARSTART":44,"COLON_TARGETS":45,"TARGETS":46,"PIPE_TARGETS":47,"SPC":48,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF2",8:"RECIPE_LINE",9:"INCLUDE",12:"EOL",13:"RULESTART",15:"COLON",18:"PIPE",20:"TARGET",21:"SEMICOLON",22:"INLINE_RECIPE",25:"VARIABLE_SET_SIMPLE",26:"VARIABLE_VALUE",27:"VARIABLE_SET_RECURSIVE",28:"VARIABLE_SET_APPEND",29:"VARIABLE_SET_CONDITIONAL",30:"VARIABLE_SET_SHELL",31:"MULTILINE_VARIABLE_SET_SIMPLE",32:"MULTILINE_VARIABLE_VALUE",33:"MULTILINE_VARIABLE_END",34:"MULTILINE_VARIABLE_SET_RECURSIVE",35:"MULTILINE_VARIABLE_SET_APPEND",36:"MULTILINE_VARIABLE_SET_CONDITIONAL",37:"MULTILINE_VARIABLE_SET_SHELL",42:"TST",44:"VARSTART",45:"COLON_TARGETS",46:"TARGETS",47:"PIPE_TARGETS",48:"SPC"},
productions_: [0,[3,2],[6,1],[6,1],[6,1],[6,1],[6,1],[4,3],[4,1],[11,0],[7,5],[16,3],[16,1],[17,3],[17,1],[14,2],[14,0],[19,2],[19,0],[10,1],[10,1],[23,2],[23,2],[23,2],[23,2],[23,2],[24,3],[24,3],[24,3],[24,3],[24,3],[38,1],[38,0],[39,2],[39,1],[40,1],[40,1],[41,2],[41,0],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
 
        resultb.end(yy);
      
break;
case 2:
 resultb.startRule(yy, _$[$0], $$[$0]); 
break;
case 3:
 resultb.recipeLine(yy, _$[$0], $$[$0]); 
break;
case 4:
 resultb.indclude(yy, _$[$0], $$[$0]); 
break;
case 5:
 resultb.defineVariable(yy, _$[$0], $$[$0]); 
break;
case 10:

      this.$ = {};
      this.$.targets0 = $$[$0-3];
      this.$.targets1 = $$[$0-1];
      this.$.targets2 = $$[$0].targets2;
      this.$.targets3 = $$[$0].targets3;
      this.$.irecipe = $$[$0].irecipe;
	
break;
case 11:

      this.$ = {};
      this.$.targets2 = $$[$0-1];
      this.$.targets3 = $$[$0].targets3;
      this.$.irecipe = $$[$0].irecipe;
	 
break;
case 12:

      this.$ = {};
      this.$.targets2 = [];
      this.$.targets3 = $$[$0].targets3;
      this.$.irecipe = $$[$0].irecipe;
 	 
break;
case 13:

      this.$ = {};
      this.$.irecipe = $$[$0];
      this.$.targets3 = $$[$0-1];
	 
break;
case 14:

      this.$ = {};
      this.$.irecipe = $$[$0];
      this.$.targets3 = [];
	 
break;
case 15:

      this.$.push({ location: _$[$0], targetName: $$[$0].trim() });
	 
break;
case 16:

      this.$ = [];
	 
break;
case 17:

	   console.error("INLINE_RECIPE = '" + $$[$0] + "'");
      this.$ = $$[$0];
	 
break;
case 18:

      this.$ = "";
	 
break;
case 19: case 20:
 this.$ = $$[$0]; 
break;
case 21:

      this.$ = { kind: 'simple', name: $$[$0-1], value: $$[$0] }
   
break;
case 22:

      this.$ = { kind: 'recursive', name: $$[$0-1], value: $$[$0] }
   
break;
case 23:

      this.$ = { kind: 'append', name: $$[$0-1], value: $$[$0] }
   
break;
case 24:

      this.$ = { kind: 'conditional', name: $$[$0-1], value: $$[$0] }
   
break;
case 25:

      this.$ = { kind: 'shell', name: $$[$0-1], value: $$[$0] }
   
break;
case 26:

      this.$ = { kind: 'simple', name: $$[$0-2], value: $$[$0-1] }
   
break;
case 27:

      this.$ = { kind: 'recursive', name: $$[$0-2], value: $$[$0-1] }
   
break;
case 28:

      this.$ = { kind: 'append', name: $$[$0-2], value: $$[$0-1] }
   
break;
case 29:

      this.$ = { kind: 'conditional', name: $$[$0-2], value: $$[$0-1] }
   
break;
case 30:

      this.$ = { kind: 'shell', name: $$[$0-2], value: $$[$0-1] }
   
break;
case 32:
 this.$ = []; 
break;
case 33:
 $$[$0-1].push($$[$0]); this.$ = $$[$0-1] 
break;
case 34:
 this.$ = [$$[$0]] 
break;
case 38:

      this.$ = 123;
      //console.error("REGISTERING");
      yy.preprocessor = { expandVariables: function (s) { console.error("REPLACING"); return "value_of_" + s; }}
   
break;
case 39:

	     console.error("INLINE_RECIPE: '" + yytext + "'");
	  
break;
case 40:

	     console.error("INCLUDE: '" + yytext + "'");
	  
break;
case 41:

	     console.error("TARGET: '" + yytext + "'");
	  
break;
case 42:

	     console.error("RULESTART: '" + yytext + "'");
	  
break;
case 43:

	     console.error("VARSTART: '" + yytext + "'");
	  
break;
case 44:

	     console.error("RECIPE_LINE: '" + yytext + "'");
	  
break;
case 45:

	     console.error("SEMICOLON: '" + yytext + "'");
	  
break;
case 46:

	     console.error("COLON: '" + yytext + "', state: " + yy.lexer.topState());
	  
break;
case 47:

	     console.error("PIPE: '" + yytext + "'");
	  
break;
case 48:

	     console.error("COLON_TARGETS: '" + yytext + "'");
	  
break;
case 49:

	     console.error("TARGETS: '" + yytext + "'");
	  
break;
case 50:

	     console.error("PIPE_TARGETS: '" + yytext + "'");
	  
break;
case 51:

	     console.error("EOL: '" + yytext + "'");
	  
break;
case 52:

	     console.error("SPC: '" + yytext + "'");
	  
break;
case 53:

	     console.error("VARIABLE_SET_SIMPLE: '" + yytext + "'");
	  
break;
case 54:

	     console.error("VARIABLE_SET_RECURSIVE: '" + yytext + "'");
	  
break;
case 55:

	     console.error("VARIABLE_SET_APPEND: '" + yytext + "'");
	  
break;
case 56:

	     console.error("VARIABLE_SET_CONDITIONAL: '" + yytext + "'");
	  
break;
case 57:

	     console.error("VARIABLE_SET_SHELL: '" + yytext + "'");
	  
break;
case 58:

	     console.error("VARIABLE_VALUE: '" + yytext + "'");
	  
break;
case 59:

	     console.error("MULTILINE_VARIABLE_SET_SIMPLE: '" + yytext + "'");
	  
break;
case 60:

	     console.error("MULTILINE_VARIABLE_SET_RECURSIVE: '" + yytext + "'");
	  
break;
case 61:

	     console.error("MULTILINE_VARIABLE_SET_APPEND: '" + yytext + "'");
	  
break;
case 62:

	     console.error("MULTILINE_VARIABLE_SET_CONDITIONAL: '" + yytext + "'");
	  
break;
case 63:

	     console.error("MULTILINE_VARIABLE_SET_SHELL: '" + yytext + "'");
	  
break;
case 64:

	     console.error("MULTILINE_VARIABLE_VALUE: '" + yytext + "'");
	  
break;
case 65:

	     console.error("MULTILINE_VARIABLE_END: '" + yytext + "'");
	  
break;
case 66:

	     console.error("EOF2: '" + yytext + "'");
	  
break;
}
},
table: [o($V0,$V1,{3:1,4:2,6:3,7:4,10:7,11:8,23:10,24:11,8:$V2,9:$V3,13:$V4,25:$V5,27:$V6,28:$V7,29:$V8,30:$V9,31:$Va,34:$Vb,35:$Vc,36:$Vd,37:$Ve}),{1:[3]},{5:[1,22],12:[1,23]},o($V0,[2,8]),o($V0,[2,2]),o($V0,[2,3]),o($V0,[2,4]),o($V0,[2,5]),o($V0,[2,6]),o([15,20],$Vf,{14:24}),o($V0,[2,19]),o($V0,[2,20]),{26:[1,25]},{26:[1,26]},{26:[1,27]},{26:[1,28]},{26:[1,29]},{32:[1,30]},{32:[1,31]},{32:[1,32]},{32:[1,33]},{32:[1,34]},{1:[2,1]},o($V0,$V1,{7:4,10:7,11:8,23:10,24:11,6:35,8:$V2,9:$V3,13:$V4,25:$V5,27:$V6,28:$V7,29:$V8,30:$V9,31:$Va,34:$Vb,35:$Vc,36:$Vd,37:$Ve}),{15:[1,36],20:$Vg},o($V0,[2,21]),o($V0,[2,22]),o($V0,[2,23]),o($V0,[2,24]),o($V0,[2,25]),{33:[1,38]},{33:[1,39]},{33:[1,40]},{33:[1,41]},{33:[1,42]},o($V0,[2,7]),o($Vh,$Vf,{14:43}),o($Vh,[2,15]),o($V0,[2,26]),o($V0,[2,27]),o($V0,[2,28]),o($V0,[2,29]),o($V0,[2,30]),o($V0,$Vi,{16:44,17:46,19:48,15:[1,45],18:$Vj,20:$Vg,21:$Vk}),o($V0,[2,10]),o([5,12,18,20,21],$Vf,{14:50}),o($V0,[2,12]),o([5,12,20,21],$Vf,{14:51}),o($V0,[2,14]),{22:[1,52]},o($V0,$Vi,{19:48,17:53,18:$Vj,20:$Vg,21:$Vk}),o($V0,$Vi,{19:54,20:$Vg,21:$Vk}),o($V0,[2,17]),o($V0,[2,11]),o($V0,[2,13])],
defaultActions: {22:[2,1]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

const result = require("../../result");
const resultb = require("./makefile-syntax-result");
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
const tokens = require("./makefile-syntax-tokens");
const variables = require("../variables");

function trimVarname(src)
{
    //console.error("VAR " + src);
    return src.replace(/^[\s]*/, "").replace(/[ =\r\n]*$/, "");
}

function trimVarvalue(src)
{
    //console.error("VAL " + src);
    return src.replace(/^[\s]*/, "").replace(/[ =\r\n]*$/, "");
}

function trimText(src, regex1, regex2)
{
    if (!src)
        return src;

    if (!!regex1)
        src = src.replace(regex1, "");

    if (!!regex2)
        src = src.replace(regex2, "");

    return src;
}

var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:
                        if (!!yy.preprocessor) 
                        {
                            var varName = trimText(yy_.yytext, /^[$][(]/, /[)]$/);
                            var varValue = yy.preprocessor.expandVariables(yy_.yytext);
                            this.unput(varValue);
                            //yy_.yytext = "";
                        }
                    
break;
case 1:
                        if (!!yy.preprocessor) 
                        {
                            var varName = trimText(yy_.yytext, /^[$][{]/, /[}]$/);
                            var varValue = yy.preprocessor.expandVariables(yy_.yytext);
                            this.unput(varValue);
                            //yy_.yytext = "";
                        }
                    
break;
case 2: this.begin("COMMENT");                          
break;
case 3: this.begin("INCLUDE"); 
break;
case 4: this.begin("RULE");    return tokens.RULESTART; 
break;
case 5: return tokens.RECIPE_LINE; 
break;
case 6: this.begin("VAR_DEF"); 
break;
case 7: return tokens.EOL; 
break;
case 8: this.begin("INITIAL"); return tokens.EOL; 
break;
case 9: this.begin("INITIAL"); return tokens.EOL; 
break;
case 10:                        return tokens.COLON; 
break;
case 11:                        return tokens.PIPE; 
break;
case 12: this.begin("IRECIPE"); return tokens.SEMICOLON; 
break;
case 13:                        return tokens.TARGET; 
break;
case 14: this.begin("RULE"); return tokens.INLINE_RECIPE; 
break;
case 15: this.begin("INITIAL"); return tokens.EOL; 
break;
case 16:
break;
case 17: return tokens.EOF2; 
break;
case 18: return tokens.EOF2; 
break;
case 19: return tokens.EOF2; 
break;
case 20: return tokens.EOF2; 
break;
case 21: return tokens.EOF2; 
break;
case 22: this.begin("VAR_VALUE"); yy_.yytext = trimVarname(yy_.yytext);  return tokens.VARIABLE_SET_RECURSIVE; 
break;
case 23: this.begin("VAR_VALUE"); yy_.yytext = trimVarname(yy_.yytext);  return tokens.VARIABLE_SET_CONDITIONAL; 
break;
case 24: this.begin("VAR_VALUE"); yy_.yytext = trimVarname(yy_.yytext);  return tokens.VARIABLE_SET_SIMPLE; 
break;
case 25: this.begin("VAR_VALUE"); yy_.yytext = trimVarname(yy_.yytext);  return tokens.VARIABLE_SET_SIMPLE; 
break;
case 26: this.begin("VAR_VALUE"); yy_.yytext = trimVarname(yy_.yytext);  return tokens.VARIABLE_SET_APPEND; 
break;
case 27: this.begin("VAR_VALUE"); yy_.yytext = trimVarname(yy_.yytext);  return tokens.VARIABLE_SET_SHELL; 
break;
case 28: this.begin("INITIAL");   yy_.yytext = trimVarvalue(yy_.yytext); return tokens.VARIABLE_VALUE; 
break;
case 29: this.begin("MULTI_VAR_DEF"); return tokens.MULTILINE_VARIABLE_SET_RECURSIVE; 
break;
case 30: this.begin("MULTI_VAR_DEF"); return tokens.MULTILINE_VARIABLE_SET_RECURSIVE; 
break;
case 31: this.begin("MULTI_VAR_DEF"); return tokens.MULTILINE_VARIABLE_SET_CONDITIONAL; 
break;
case 32: this.begin("MULTI_VAR_DEF"); return tokens.MULTILINE_VARIABLE_SET_SIMPLE; 
break;
case 33: this.begin("MULTI_VAR_DEF"); return tokens.MULTILINE_VARIABLE_SET_SIMPLE; 
break;
case 34: this.begin("MULTI_VAR_DEF"); return tokens.MULTILINE_VARIABLE_SET_APPEND; 
break;
case 35: this.begin("MULTI_VAR_DEF"); return tokens.MULTILINE_VARIABLE_SET_SHELL; 
break;
case 36: return tokens.MULTILINE_VARIABLE_VALUE; 
break;
case 37: this.begin("INITIAL"); console.error("MultiVar enddef => INITIAL"); return tokens.MULTILINE_VARIABLE_END; 
break;
case 38: console.error("MISMATCH: '" + yy_.yytext + "', state: " + this.topState()); 
break;
}
},
rules: [/^(?:[$][(]\w+[)])/,/^(?:[$][{]\w+[}])/,/^(?:#)/,/^(?:include\s+)/,/^(?:(?=(((?:(?:((?:(?:([^\s\\])|((?:\\[\x20:\t|\\])))+))([ \t]*))*([ \t]*)))[:])))/,/^(?:[ \t]+((?:[^\n\r]*)))/,/^(?:(?=((?:[^\s=:?+!])+)\s*.?.?=))/,/^(?:((?:[\r]?[\n])))/,/^(?:[^\n\r]*$)/,/^(?:[#].*((?:[\r]?[\n])))/,/^(?:[:])/,/^(?:[|])/,/^(?:[;])/,/^(?:(?:((?:(?:([^\s\\])|((?:\\[\x20:\t|\\])))+))))/,/^(?:((?:[^\n\r]*)))/,/^(?:((?:[\r]?[\n])))/,/^(?:[ \t]+)/,/^(?:$)/,/^(?:$)/,/^(?:$)/,/^(?:$)/,/^(?:$)/,/^(?:((?:[^\s=:?+!])+)\s*=)/,/^(?:((?:[^\s=:?+!])+)\s*\?=)/,/^(?:((?:[^\s=:?+!])+)\s*:=)/,/^(?:((?:[^\s=:?+!])+)\s*::=)/,/^(?:((?:[^\s=:?+!])+)\s*\+=)/,/^(?:((?:[^\s=:?+!])+)\s*!=)/,/^(?:[^\r\n]*(?=((?:[\r]?[\n]))))/,/^(?:define[ \t]+((?:[^\s=:?+!])+)[ \t]*[\n])/,/^(?:define[ \t]+((?:[^\s=:?+!])+)[ \t]*=[ \t]*[\n])/,/^(?:define[ \t]+((?:[^\s=:?+!])+)[ \t]*\?=[ \t]*[\n])/,/^(?:define[ \t]+((?:[^\s=:?+!])+)[ \t]*:=[ \t]*[\n])/,/^(?:define[ \t]+((?:[^\s=:?+!])+)[ \t]*::=[ \t]*[\n])/,/^(?:define[ \t]+((?:[^\s=:?+!])+)[ \t]*\+=[ \t]*[\n])/,/^(?:define[ \t]+((?:[^\s=:?+!])+)[ \t]*!=[ \t]*[\n])/,/^(?:^(?!enddef)[^\n]*\n)/,/^(?:enddef\s*\n)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,17,29,30,31,32,33,34,35,38],"inclusive":true},"RULE":{"rules":[0,1,9,10,11,12,13,15,16,17,18,38],"inclusive":true},"INCLUDE":{"rules":[0,1,17,38],"inclusive":true},"COMMENT":{"rules":[0,1,8,17,38],"inclusive":true},"VAR_DEF":{"rules":[0,1,17,21,22,23,24,25,26,27,38],"inclusive":true},"VAR_VALUE":{"rules":[0,1,17,28,38],"inclusive":true},"MULTI_VAR_DEF":{"rules":[0,1,17,20,36,37,38],"inclusive":true},"IRECIPE":{"rules":[0,1,14,17,19,38],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = tst;
exports.Parser = tst.Parser;
exports.parse = function () { return tst.parse.apply(tst, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}