const INLINE_RECIPE = "INLINE_RECIPE";
const TARGET = "TARGET";
export const RULESTART = "RULESTART";
const COLON_TARGETS = "COLON_TARGETS";
const TARGETS = "TARGETS";
const PIPE_TARGETS = "PIPE_TARGETS";
const RECIPE_LINE = "RECIPE_LINE";
const EOL = "EOL";
const EOF = "EOF";
const SPC = "SPC";
const VARIABLE_SET = "VARIABLE_SET";
const VARIABLE_VALUE = "VARIABLE_VALUE";
const MULTILINE_VARIABLE_SET = "MULTILINE_VARIABLE_SET";
const MULTILINE_VARIABLE_VALUE = "MULTILINE_VARIABLE_VALUE";
const MULTILINE_VARIABLE_END = "MULTILINE_VARIABLE_END";
 